#!/bin/sh

docker run --rm --user $(id -u):$(id -g) \
	-v ${PWD}:/local openapitools/openapi-generator-cli generate \
	-i /local/immich-openapi-specs.json \
	-g rust \
	-o /local/crates/openapi_client
