/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.103.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddUsersDto {
    #[serde(rename = "albumUsers")]
    pub album_users: Vec<models::AlbumUserAddDto>,
    /// This property was deprecated in v1.102.0
    #[serde(rename = "sharedUserIds", skip_serializing_if = "Option::is_none")]
    pub shared_user_ids: Option<Vec<uuid::Uuid>>,
}

impl AddUsersDto {
    pub fn new(album_users: Vec<models::AlbumUserAddDto>) -> AddUsersDto {
        AddUsersDto {
            album_users,
            shared_user_ids: None,
        }
    }
}

