/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.103.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetFileUploadResponseDto {
    #[serde(rename = "duplicate")]
    pub duplicate: bool,
    #[serde(rename = "id")]
    pub id: String,
}

impl AssetFileUploadResponseDto {
    pub fn new(duplicate: bool, id: String) -> AssetFileUploadResponseDto {
        AssetFileUploadResponseDto {
            duplicate,
            id,
        }
    }
}

