/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.103.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LibraryType {
    #[serde(rename = "UPLOAD")]
    Upload,
    #[serde(rename = "EXTERNAL")]
    External,

}

impl std::fmt::Display for LibraryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Upload => write!(f, "UPLOAD"),
            Self::External => write!(f, "EXTERNAL"),
        }
    }
}

impl Default for LibraryType {
    fn default() -> LibraryType {
        Self::Upload
    }
}

