/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.103.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemoryLaneResponseDto {
    #[serde(rename = "assets")]
    pub assets: Vec<models::AssetResponseDto>,
    /// This property was deprecated in v1.100.0
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "yearsAgo")]
    pub years_ago: i32,
}

impl MemoryLaneResponseDto {
    pub fn new(assets: Vec<models::AssetResponseDto>, title: String, years_ago: i32) -> MemoryLaneResponseDto {
        MemoryLaneResponseDto {
            assets,
            title,
            years_ago,
        }
    }
}

