/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.103.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemConfigMachineLearningDto {
    #[serde(rename = "clip")]
    pub clip: Box<models::ClipConfig>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "facialRecognition")]
    pub facial_recognition: Box<models::RecognitionConfig>,
    #[serde(rename = "url")]
    pub url: String,
}

impl SystemConfigMachineLearningDto {
    pub fn new(clip: models::ClipConfig, enabled: bool, facial_recognition: models::RecognitionConfig, url: String) -> SystemConfigMachineLearningDto {
        SystemConfigMachineLearningDto {
            clip: Box::new(clip),
            enabled,
            facial_recognition: Box::new(facial_recognition),
            url,
        }
    }
}

