/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.103.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserDto {
    #[serde(rename = "avatarColor", skip_serializing_if = "Option::is_none")]
    pub avatar_color: Option<models::UserAvatarColor>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "isAdmin", skip_serializing_if = "Option::is_none")]
    pub is_admin: Option<bool>,
    #[serde(rename = "memoriesEnabled", skip_serializing_if = "Option::is_none")]
    pub memories_enabled: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "quotaSizeInBytes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quota_size_in_bytes: Option<Option<i64>>,
    #[serde(rename = "shouldChangePassword", skip_serializing_if = "Option::is_none")]
    pub should_change_password: Option<bool>,
    #[serde(rename = "storageLabel", skip_serializing_if = "Option::is_none")]
    pub storage_label: Option<String>,
}

impl UpdateUserDto {
    pub fn new(id: uuid::Uuid) -> UpdateUserDto {
        UpdateUserDto {
            avatar_color: None,
            email: None,
            id,
            is_admin: None,
            memories_enabled: None,
            name: None,
            password: None,
            quota_size_in_bytes: None,
            should_change_password: None,
            storage_label: None,
        }
    }
}

