/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.103.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserDto {
    #[serde(rename = "avatarColor")]
    pub avatar_color: models::UserAvatarColor,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "profileImagePath")]
    pub profile_image_path: String,
}

impl UserDto {
    pub fn new(avatar_color: models::UserAvatarColor, email: String, id: String, name: String, profile_image_path: String) -> UserDto {
        UserDto {
            avatar_color,
            email,
            id,
            name,
            profile_image_path,
        }
    }
}

